version: "3.9"
services:
  web:
    build: ./src/web/
    environment:
      - AUTH_ADDRESS=auth
      - FARM_ADDRESS=farm
      - STORE_ADDRESS=store
      - DATA_ADDRESS=data
    ports:
      - "9090:80"

#TODO add auth,data,farmer,store
